name: flutter_zoom_plugin
description: A flutter plugin for the Zoom SDK.
version: 0.0.7
homepage: https://decodedhealth.com
issue_tracker: https://github.com/decodedhealth/flutter_zoom_plugin/issues
environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.decodedhealth.flutter_zoom_plugin
        pluginClass: FlutterZoomPlugin
      ios:
        pluginClass: FlutterZoomPlugin
